services:
  chunk-uploader-service:    
    build: .
    container_name: chunk-uploader-service
    env_file:
      - .env
    ports:
      - "${CHUNK_SERVICE_HOST_PORT}:${CHUNK_SERVICE_CONTAINER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
      - ./chunks:/app/chunks
      - ./merged-files:/app/merged-files
volumes:
  chunks:
  merged-files:
