services:
  chunk-uploader-service:
    build: .
    ports:
      - "${CHUNK_SERVICE_HOST_PORT}:${CHUNK_SERVICE_CONTAINER_PORT}"
    volumes:
      - .:/app
      - ./chunks:/app/chunks
      - ./output:/app/output